
package org.choreos.services.client.shoppingassistantapp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShoppingassistantappService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/services/shoppingassistantapp/src/main/webapp/WEB-INF/wsdl/shoppingassistantapp.wsdl")
public class ShoppingassistantappService
    extends Service
{

    private final static URL SHOPPINGASSISTANTAPPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPPINGASSISTANTAPPSERVICE_EXCEPTION;
    private final static QName SHOPPINGASSISTANTAPPSERVICE_QNAME = new QName("http://services.choreos.org/", "ShoppingassistantappService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/services/shoppingassistantapp/src/main/webapp/WEB-INF/wsdl/shoppingassistantapp.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPPINGASSISTANTAPPSERVICE_WSDL_LOCATION = url;
        SHOPPINGASSISTANTAPPSERVICE_EXCEPTION = e;
    }

    public ShoppingassistantappService() {
        super(__getWsdlLocation(), SHOPPINGASSISTANTAPPSERVICE_QNAME);
    }

    public ShoppingassistantappService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPPINGASSISTANTAPPSERVICE_QNAME, features);
    }

    public ShoppingassistantappService(URL wsdlLocation) {
        super(wsdlLocation, SHOPPINGASSISTANTAPPSERVICE_QNAME);
    }

    public ShoppingassistantappService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPPINGASSISTANTAPPSERVICE_QNAME, features);
    }

    public ShoppingassistantappService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShoppingassistantappService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Shoppingassistantapp
     */
    @WebEndpoint(name = "ShoppingassistantappPort")
    public Shoppingassistantapp getShoppingassistantappPort() {
        return super.getPort(new QName("http://services.choreos.org/", "ShoppingassistantappPort"), Shoppingassistantapp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Shoppingassistantapp
     */
    @WebEndpoint(name = "ShoppingassistantappPort")
    public Shoppingassistantapp getShoppingassistantappPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "ShoppingassistantappPort"), Shoppingassistantapp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPPINGASSISTANTAPPSERVICE_EXCEPTION!= null) {
            throw SHOPPINGASSISTANTAPPSERVICE_EXCEPTION;
        }
        return SHOPPINGASSISTANTAPPSERVICE_WSDL_LOCATION;
    }

}
