
package org.choreos.services.enactchoreography.client.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/client.wsdl")
public class ClientService
    extends Service
{

    private final static URL CLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSERVICE_EXCEPTION;
    private final static QName CLIENTSERVICE_QNAME = new QName("http://services.choreos.org/", "ClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/client.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSERVICE_WSDL_LOCATION = url;
        CLIENTSERVICE_EXCEPTION = e;
    }

    public ClientService() {
        super(__getWsdlLocation(), CLIENTSERVICE_QNAME);
    }

    public ClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSERVICE_QNAME, features);
    }

    public ClientService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSERVICE_QNAME);
    }

    public ClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSERVICE_QNAME, features);
    }

    public ClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Client
     */
    @WebEndpoint(name = "ClientPort")
    public Client getClientPort() {
        return super.getPort(new QName("http://services.choreos.org/", "ClientPort"), Client.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Client
     */
    @WebEndpoint(name = "ClientPort")
    public Client getClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "ClientPort"), Client.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSERVICE_EXCEPTION!= null) {
            throw CLIENTSERVICE_EXCEPTION;
        }
        return CLIENTSERVICE_WSDL_LOCATION;
    }

}
