
package org.choreos.services.client.instoretotem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InStoreTotemService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/services/instoretotem/src/main/webapp/WEB-INF/wsdl/instoretotem.wsdl")
public class InStoreTotemService
    extends Service
{

    private final static URL INSTORETOTEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSTORETOTEMSERVICE_EXCEPTION;
    private final static QName INSTORETOTEMSERVICE_QNAME = new QName("http://services.choreos.org/", "InStoreTotemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/services/instoretotem/src/main/webapp/WEB-INF/wsdl/instoretotem.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSTORETOTEMSERVICE_WSDL_LOCATION = url;
        INSTORETOTEMSERVICE_EXCEPTION = e;
    }

    public InStoreTotemService() {
        super(__getWsdlLocation(), INSTORETOTEMSERVICE_QNAME);
    }

    public InStoreTotemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSTORETOTEMSERVICE_QNAME, features);
    }

    public InStoreTotemService(URL wsdlLocation) {
        super(wsdlLocation, INSTORETOTEMSERVICE_QNAME);
    }

    public InStoreTotemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSTORETOTEMSERVICE_QNAME, features);
    }

    public InStoreTotemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InStoreTotemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InStoreTotem
     */
    @WebEndpoint(name = "InStoreTotemPort")
    public InStoreTotem getInStoreTotemPort() {
        return super.getPort(new QName("http://services.choreos.org/", "InStoreTotemPort"), InStoreTotem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InStoreTotem
     */
    @WebEndpoint(name = "InStoreTotemPort")
    public InStoreTotem getInStoreTotemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "InStoreTotemPort"), InStoreTotem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSTORETOTEMSERVICE_EXCEPTION!= null) {
            throw INSTORETOTEMSERVICE_EXCEPTION;
        }
        return INSTORETOTEMSERVICE_WSDL_LOCATION;
    }

}
