
package org.choreos.services.enactchoreography.client.marketingmanager;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MarketingManager", targetNamespace = "http://services.choreos.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MarketingManager {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "scenarioSetup", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.ScenarioSetup")
    @ResponseWrapper(localName = "scenarioSetupResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.ScenarioSetupResponse")
    @Action(input = "http://services.choreos.org/MarketingManager/scenarioSetupRequest", output = "http://services.choreos.org/MarketingManager/scenarioSetupResponse")
    public void scenarioSetup();

    /**
     * 
     * @param estimationNeedAlert
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "putEstimationReq", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.PutEstimationReq")
    @ResponseWrapper(localName = "putEstimationReqResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.PutEstimationReqResponse")
    @Action(input = "http://services.choreos.org/MarketingManager/putEstimationReqRequest", output = "http://services.choreos.org/MarketingManager/putEstimationReqResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/MarketingManager/putEstimationReq/Fault/ScenarioException")
    })
    public void putEstimationReq(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "estimationNeedAlert", targetNamespace = "")
        EstimationNeedAlert estimationNeedAlert)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param product
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "requestPrivateOffer", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.RequestPrivateOffer")
    @ResponseWrapper(localName = "requestPrivateOfferResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.RequestPrivateOfferResponse")
    @Action(input = "http://services.choreos.org/MarketingManager/requestPrivateOfferRequest", output = "http://services.choreos.org/MarketingManager/requestPrivateOfferResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/MarketingManager/requestPrivateOffer/Fault/ScenarioException")
    })
    public void requestPrivateOffer(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "product", targetNamespace = "")
        Product product)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "requestPublicOffer", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.RequestPublicOffer")
    @ResponseWrapper(localName = "requestPublicOfferResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.RequestPublicOfferResponse")
    @Action(input = "http://services.choreos.org/MarketingManager/requestPublicOfferRequest", output = "http://services.choreos.org/MarketingManager/requestPublicOfferResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/MarketingManager/requestPublicOffer/Fault/ScenarioException")
    })
    public void requestPublicOffer(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setInvocationAddress", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.SetInvocationAddress")
    @ResponseWrapper(localName = "setInvocationAddressResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.SetInvocationAddressResponse")
    @Action(input = "http://services.choreos.org/MarketingManager/setInvocationAddressRequest", output = "http://services.choreos.org/MarketingManager/setInvocationAddressResponse")
    public void setInvocationAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setEndpointAddress", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.SetEndpointAddress")
    @ResponseWrapper(localName = "setEndpointAddressResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.marketingmanager.SetEndpointAddressResponse")
    @Action(input = "http://services.choreos.org/MarketingManager/setEndpointAddressRequest", output = "http://services.choreos.org/MarketingManager/setEndpointAddressResponse")
    public void setEndpointAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
