
package org.choreos.services.enactchoreography.client.marketingmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MarketingManagerService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/marketingmanager.wsdl")
public class MarketingManagerService
    extends Service
{

    private final static URL MARKETINGMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MARKETINGMANAGERSERVICE_EXCEPTION;
    private final static QName MARKETINGMANAGERSERVICE_QNAME = new QName("http://services.choreos.org/", "MarketingManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/marketingmanager.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARKETINGMANAGERSERVICE_WSDL_LOCATION = url;
        MARKETINGMANAGERSERVICE_EXCEPTION = e;
    }

    public MarketingManagerService() {
        super(__getWsdlLocation(), MARKETINGMANAGERSERVICE_QNAME);
    }

    public MarketingManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARKETINGMANAGERSERVICE_QNAME, features);
    }

    public MarketingManagerService(URL wsdlLocation) {
        super(wsdlLocation, MARKETINGMANAGERSERVICE_QNAME);
    }

    public MarketingManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARKETINGMANAGERSERVICE_QNAME, features);
    }

    public MarketingManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketingManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarketingManager
     */
    @WebEndpoint(name = "MarketingManagerPort")
    public MarketingManager getMarketingManagerPort() {
        return super.getPort(new QName("http://services.choreos.org/", "MarketingManagerPort"), MarketingManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketingManager
     */
    @WebEndpoint(name = "MarketingManagerPort")
    public MarketingManager getMarketingManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "MarketingManagerPort"), MarketingManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARKETINGMANAGERSERVICE_EXCEPTION!= null) {
            throw MARKETINGMANAGERSERVICE_EXCEPTION;
        }
        return MARKETINGMANAGERSERVICE_WSDL_LOCATION;
    }

}
