
package org.choreos.services.cd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShopEntranceService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/rest/cd-generator/examples/wp7/cd/CD-client-shopentrance/src/main/webapp/WEB-INF/wsdl/CD-client-shopentrance.wsdl")
public class ShopEntranceService
    extends Service
{

    private final static URL SHOPENTRANCESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPENTRANCESERVICE_EXCEPTION;
    private final static QName SHOPENTRANCESERVICE_QNAME = new QName("http://services.choreos.org/", "ShopEntranceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/rest/cd-generator/examples/wp7/cd/CD-client-shopentrance/src/main/webapp/WEB-INF/wsdl/CD-client-shopentrance.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPENTRANCESERVICE_WSDL_LOCATION = url;
        SHOPENTRANCESERVICE_EXCEPTION = e;
    }

    public ShopEntranceService() {
        super(__getWsdlLocation(), SHOPENTRANCESERVICE_QNAME);
    }

    public ShopEntranceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPENTRANCESERVICE_QNAME, features);
    }

    public ShopEntranceService(URL wsdlLocation) {
        super(wsdlLocation, SHOPENTRANCESERVICE_QNAME);
    }

    public ShopEntranceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPENTRANCESERVICE_QNAME, features);
    }

    public ShopEntranceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopEntranceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShopEntrance
     */
    @WebEndpoint(name = "ShopEntrancePort")
    public ShopEntrance getShopEntrancePort() {
        return super.getPort(new QName("http://services.choreos.org/", "ShopEntrancePort"), ShopEntrance.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShopEntrance
     */
    @WebEndpoint(name = "ShopEntrancePort")
    public ShopEntrance getShopEntrancePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "ShopEntrancePort"), ShopEntrance.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPENTRANCESERVICE_EXCEPTION!= null) {
            throw SHOPENTRANCESERVICE_EXCEPTION;
        }
        return SHOPENTRANCESERVICE_WSDL_LOCATION;
    }

}
