
package org.choreos.services.enactchoreography.client.selfcheckoutmachine;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SelfCheckOutMachineService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/selfcheckoutmachine.wsdl")
public class SelfCheckOutMachineService
    extends Service
{

    private final static URL SELFCHECKOUTMACHINESERVICE_WSDL_LOCATION;
    private final static WebServiceException SELFCHECKOUTMACHINESERVICE_EXCEPTION;
    private final static QName SELFCHECKOUTMACHINESERVICE_QNAME = new QName("http://services.choreos.org/", "SelfCheckOutMachineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/selfcheckoutmachine.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELFCHECKOUTMACHINESERVICE_WSDL_LOCATION = url;
        SELFCHECKOUTMACHINESERVICE_EXCEPTION = e;
    }

    public SelfCheckOutMachineService() {
        super(__getWsdlLocation(), SELFCHECKOUTMACHINESERVICE_QNAME);
    }

    public SelfCheckOutMachineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELFCHECKOUTMACHINESERVICE_QNAME, features);
    }

    public SelfCheckOutMachineService(URL wsdlLocation) {
        super(wsdlLocation, SELFCHECKOUTMACHINESERVICE_QNAME);
    }

    public SelfCheckOutMachineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELFCHECKOUTMACHINESERVICE_QNAME, features);
    }

    public SelfCheckOutMachineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfCheckOutMachineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SelfCheckOutMachine
     */
    @WebEndpoint(name = "SelfCheckOutMachinePort")
    public SelfCheckOutMachine getSelfCheckOutMachinePort() {
        return super.getPort(new QName("http://services.choreos.org/", "SelfCheckOutMachinePort"), SelfCheckOutMachine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfCheckOutMachine
     */
    @WebEndpoint(name = "SelfCheckOutMachinePort")
    public SelfCheckOutMachine getSelfCheckOutMachinePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "SelfCheckOutMachinePort"), SelfCheckOutMachine.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELFCHECKOUTMACHINESERVICE_EXCEPTION!= null) {
            throw SELFCHECKOUTMACHINESERVICE_EXCEPTION;
        }
        return SELFCHECKOUTMACHINESERVICE_WSDL_LOCATION;
    }

}
