
package org.choreos.services.enactchoreography.client.basiccommunicationdevice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BasicCommunicationDeviceService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/basiccommunicationdevice.wsdl")
public class BasicCommunicationDeviceService
    extends Service
{

    private final static URL BASICCOMMUNICATIONDEVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BASICCOMMUNICATIONDEVICESERVICE_EXCEPTION;
    private final static QName BASICCOMMUNICATIONDEVICESERVICE_QNAME = new QName("http://services.choreos.org/", "BasicCommunicationDeviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/examples/wp7/starters/startWP7Choreography/src/main/resources/wsdl/basiccommunicationdevice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASICCOMMUNICATIONDEVICESERVICE_WSDL_LOCATION = url;
        BASICCOMMUNICATIONDEVICESERVICE_EXCEPTION = e;
    }

    public BasicCommunicationDeviceService() {
        super(__getWsdlLocation(), BASICCOMMUNICATIONDEVICESERVICE_QNAME);
    }

    public BasicCommunicationDeviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASICCOMMUNICATIONDEVICESERVICE_QNAME, features);
    }

    public BasicCommunicationDeviceService(URL wsdlLocation) {
        super(wsdlLocation, BASICCOMMUNICATIONDEVICESERVICE_QNAME);
    }

    public BasicCommunicationDeviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASICCOMMUNICATIONDEVICESERVICE_QNAME, features);
    }

    public BasicCommunicationDeviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicCommunicationDeviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BasicCommunicationDevice
     */
    @WebEndpoint(name = "BasicCommunicationDevicePort")
    public BasicCommunicationDevice getBasicCommunicationDevicePort() {
        return super.getPort(new QName("http://services.choreos.org/", "BasicCommunicationDevicePort"), BasicCommunicationDevice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BasicCommunicationDevice
     */
    @WebEndpoint(name = "BasicCommunicationDevicePort")
    public BasicCommunicationDevice getBasicCommunicationDevicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "BasicCommunicationDevicePort"), BasicCommunicationDevice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASICCOMMUNICATIONDEVICESERVICE_EXCEPTION!= null) {
            throw BASICCOMMUNICATIONDEVICESERVICE_EXCEPTION;
        }
        return BASICCOMMUNICATIONDEVICESERVICE_WSDL_LOCATION;
    }

}
