
package org.choreos.services.enactchoreography.client.shoppingassistantapp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Shoppingassistantapp", targetNamespace = "http://services.choreos.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Shoppingassistantapp {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "scenarioSetup", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.ScenarioSetup")
    @ResponseWrapper(localName = "scenarioSetupResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.ScenarioSetupResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/scenarioSetupRequest", output = "http://services.choreos.org/Shoppingassistantapp/scenarioSetupResponse")
    public void scenarioSetup();

    /**
     * 
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "shopAssistAppSubscribe", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.ShopAssistAppSubscribe")
    @ResponseWrapper(localName = "shopAssistAppSubscribeResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.ShopAssistAppSubscribeResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/shopAssistAppSubscribeRequest", output = "http://services.choreos.org/Shoppingassistantapp/shopAssistAppSubscribeResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/shopAssistAppSubscribe/Fault/ScenarioException")
    })
    public void shopAssistAppSubscribe(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "shopAssistAppUnsubscribe", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.ShopAssistAppUnsubscribe")
    @ResponseWrapper(localName = "shopAssistAppUnsubscribeResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.ShopAssistAppUnsubscribeResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/shopAssistAppUnsubscribeRequest", output = "http://services.choreos.org/Shoppingassistantapp/shopAssistAppUnsubscribeResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/shopAssistAppUnsubscribe/Fault/ScenarioException")
    })
    public void shopAssistAppUnsubscribe(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param offer
     * @throws ScenarioException_Exception
     */
    @WebMethod(operationName = "private_offer")
    @RequestWrapper(localName = "private_offer", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.PrivateOffer")
    @ResponseWrapper(localName = "private_offerResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.PrivateOfferResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/private_offerRequest", output = "http://services.choreos.org/Shoppingassistantapp/private_offerResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/private_offer/Fault/ScenarioException")
    })
    public void privateOffer(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "offer", targetNamespace = "")
        Offer offer)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param items
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod(operationName = "record_bought_items")
    @RequestWrapper(localName = "record_bought_items", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.RecordBoughtItems")
    @ResponseWrapper(localName = "record_bought_itemsResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.RecordBoughtItemsResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/record_bought_itemsRequest", output = "http://services.choreos.org/Shoppingassistantapp/record_bought_itemsResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/record_bought_items/Fault/ScenarioException")
    })
    public void recordBoughtItems(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "items", targetNamespace = "")
        List<Product> items)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param q
     * @throws ScenarioException_Exception
     */
    @WebMethod(operationName = "communicate_questionnaire")
    @RequestWrapper(localName = "communicate_questionnaire", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.CommunicateQuestionnaire")
    @ResponseWrapper(localName = "communicate_questionnaireResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.CommunicateQuestionnaireResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/communicate_questionnaireRequest", output = "http://services.choreos.org/Shoppingassistantapp/communicate_questionnaireResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/communicate_questionnaire/Fault/ScenarioException")
    })
    public void communicateQuestionnaire(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "q", targetNamespace = "")
        Questionnaire q)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param rem
     * @throws ScenarioException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "remind", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.Remind")
    @ResponseWrapper(localName = "remindResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.RemindResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/remindRequest", output = "http://services.choreos.org/Shoppingassistantapp/remindResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/remind/Fault/ScenarioException")
    })
    public void remind(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "rem", targetNamespace = "")
        Reminder rem)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param inc
     * @param sessionId
     * @throws ScenarioException_Exception
     */
    @WebMethod(operationName = "communicate_incentive")
    @RequestWrapper(localName = "communicate_incentive", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.CommunicateIncentive")
    @ResponseWrapper(localName = "communicate_incentiveResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.CommunicateIncentiveResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/communicate_incentiveRequest", output = "http://services.choreos.org/Shoppingassistantapp/communicate_incentiveResponse", fault = {
        @FaultAction(className = ScenarioException_Exception.class, value = "http://services.choreos.org/Shoppingassistantapp/communicate_incentive/Fault/ScenarioException")
    })
    public void communicateIncentive(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "inc", targetNamespace = "")
        Specialoffer inc)
        throws ScenarioException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setInvocationAddress", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.SetInvocationAddress")
    @ResponseWrapper(localName = "setInvocationAddressResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.SetInvocationAddressResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/setInvocationAddressRequest", output = "http://services.choreos.org/Shoppingassistantapp/setInvocationAddressResponse")
    public void setInvocationAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setEndpointAddress", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.SetEndpointAddress")
    @ResponseWrapper(localName = "setEndpointAddressResponse", targetNamespace = "http://services.choreos.org/", className = "org.choreos.services.enactchoreography.client.shoppingassistantapp.SetEndpointAddressResponse")
    @Action(input = "http://services.choreos.org/Shoppingassistantapp/setEndpointAddressRequest", output = "http://services.choreos.org/Shoppingassistantapp/setEndpointAddressResponse")
    public void setEndpointAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
