 /*
 * Copyright 2015 The CHOReVOLUTION project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCoordinationChannel", targetNamespace = "http://eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCoordinationChannel {


    /**
     * 
     * @param additionalMessage
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "update", targetNamespace = "http://eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client/", className = "eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client.Update")
    @Action(input = "http://eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client/WSCoordinationChannelService/update")
    public void update(
        @WebParam(name = "additionalMessage", targetNamespace = "")
        AdditionalMessageUpdate additionalMessage);

    /**
     * 
     * @param additionalMessageNotify
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "notify", targetNamespace = "http://eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client/", className = "eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client.Notify")
    @Action(input = "http://eu.chorevolution.synthesisprocessor.coordinationprotocol.channel.client/WSCoordinationChannelService/notify")
    public void notify(
        @WebParam(name = "additionalMessageNotify", targetNamespace = "")
        AdditionalMessageNotify additionalMessageNotify);

}
