
package org.choreos.services.cd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmartCartService", targetNamespace = "http://services.choreos.org/", wsdlLocation = "file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/rest/cd-generator/examples/wp7/cd/CD-selfcheckoutmachine-smartcart/src/main/webapp/WEB-INF/wsdl/CD-selfcheckoutmachine-smartcart.wsdl")
public class SmartCartService
    extends Service
{

    private final static URL SMARTCARTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMARTCARTSERVICE_EXCEPTION;
    private final static QName SMARTCARTSERVICE_QNAME = new QName("http://services.choreos.org/", "SmartCartService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/alexander/Sviluppo/CHOReOS/choreosynt/rest/cd-generator/examples/wp7/cd/CD-selfcheckoutmachine-smartcart/src/main/webapp/WEB-INF/wsdl/CD-selfcheckoutmachine-smartcart.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMARTCARTSERVICE_WSDL_LOCATION = url;
        SMARTCARTSERVICE_EXCEPTION = e;
    }

    public SmartCartService() {
        super(__getWsdlLocation(), SMARTCARTSERVICE_QNAME);
    }

    public SmartCartService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMARTCARTSERVICE_QNAME, features);
    }

    public SmartCartService(URL wsdlLocation) {
        super(wsdlLocation, SMARTCARTSERVICE_QNAME);
    }

    public SmartCartService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMARTCARTSERVICE_QNAME, features);
    }

    public SmartCartService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmartCartService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmartCart
     */
    @WebEndpoint(name = "SmartCartPort")
    public SmartCart getSmartCartPort() {
        return super.getPort(new QName("http://services.choreos.org/", "SmartCartPort"), SmartCart.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmartCart
     */
    @WebEndpoint(name = "SmartCartPort")
    public SmartCart getSmartCartPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.choreos.org/", "SmartCartPort"), SmartCart.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMARTCARTSERVICE_EXCEPTION!= null) {
            throw SMARTCARTSERVICE_EXCEPTION;
        }
        return SMARTCARTSERVICE_WSDL_LOCATION;
    }

}
